name: Chrome Extension

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install -g npm@8.12.2
      - run: npm ci
      - run: npm run chrome.build
      - run: cd chrome/dist && zip -r aicacia-journal-chrome-extension.zip .
      - id: tag
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ journal.GITHUB_TOKEN }}
        with:
          tag_name: 'aicacia-journal-chrome-extension-${{ steps.tag.outputs.sha_short }}'
          release_name: 'Aicacia Journal Chrome Extension ${{ steps.tag.outputs.sha_short }}'
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ journal.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chrome/dist/aicacia-journal-chrome-extension.zip
          asset_name: aicacia-journal-chrome-extension.zip
          asset_content_type: application/zip
