name: Desktop

on:
  push:
    branches: [main]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - run: npm install -g npm@8.12.2
      - run: npm ci
      - run: npm run desktop.build -- --verbose
      - id: tag
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ journal.GITHUB_TOKEN }}
        with:
          tagName: aicacia-journal-desktop-${{ steps.tag.outputs.sha_short }}
          releaseName: 'Aicacia Journal Desktop ${{ steps.tag.outputs.sha_short }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
